name: Build IPA
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout code with submodules
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'

      # 调试：列出目录结构，确认文件位置
      - name: Debug - List files
        run: ls -la

      - name: Write config
        run: echo "${{ secrets.SECRETS_XCCONFIG }}" > Sources/AsideMusic/Secrets.xcconfig

      - name: Chmod
        run: chmod +x build_ipa.sh

      - name: Build
        run: ./build_ipa.sh

      - uses: actions/upload-artifact@v4
        with:
          name: AsideMusic
          path: AsideMusic.ipa
