name: Build IPA
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Write config
        run: echo "${{ secrets.SECRETS_XCCONFIG }}" > Secrets.xcconfig
      
      - name: Chmod
        run: chmod +x scripts/build_ipa.sh
      
      - name: Build
        run: ./scripts/build_ipa.sh
      
      - uses: actions/upload-artifact@v4
        with:
          name: AsideMusic
          path: AsideMusic.ipa
